services:
  - type: web
    name: bitvault-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: bitvault-database
          property: connectionString
    autoDeploy: false

databases:
  - name: bitvault-database
    databaseName: bitvault_pro
    user: bitvault_user
    plan: free