services:
  - type: web
    name: corex-app
    env: node
    plan: free
    buildCommand: npm ci && npx vite build && npx esbuild server/index.ts --platform=node --target=node18 --packages=external --bundle --format=esm --outfile=dist/index.js --external:pg-native --external:@neondatabase/serverless
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: corex-database
          property: connectionString
    autoDeploy: false

databases:
  - name: corex-database
    databaseName: corex
    user: corex_user
    plan: free