
-- Add baseline statistics columns to admin_config table
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS baseline_users INTEGER NOT NULL DEFAULT 420;
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS baseline_active_investments INTEGER NOT NULL DEFAULT 804;
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS baseline_total_balance DECIMAL(18,8) NOT NULL DEFAULT '70275.171605';
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS baseline_total_profit DECIMAL(18,8) NOT NULL DEFAULT '460.347340';

-- Plan baseline data columns
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS growth_plan_active INTEGER NOT NULL DEFAULT 227;
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS growth_plan_amount DECIMAL(18,8) NOT NULL DEFAULT '11004.9901';
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS growth_plan_profit DECIMAL(18,8) NOT NULL DEFAULT '101.649889';

ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS institutional_plan_active INTEGER NOT NULL DEFAULT 210;
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS institutional_plan_amount DECIMAL(18,8) NOT NULL DEFAULT '9228.4977';
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS institutional_plan_profit DECIMAL(18,8) NOT NULL DEFAULT '205.248890';

ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS premium_plan_active INTEGER NOT NULL DEFAULT 198;
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS premium_plan_amount DECIMAL(18,8) NOT NULL DEFAULT '9274.8974';
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS premium_plan_profit DECIMAL(18,8) NOT NULL DEFAULT '114.419514';

ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS foundation_plan_active INTEGER NOT NULL DEFAULT 169;
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS foundation_plan_amount DECIMAL(18,8) NOT NULL DEFAULT '7436.5081';
ALTER TABLE admin_config ADD COLUMN IF NOT EXISTS foundation_plan_profit DECIMAL(18,8) NOT NULL DEFAULT '39.029047';
