import TelegramBot from 'node-telegram-bot-api';

// Initialize Telegram Bot
const botToken = process.env.TELEGRAM_BOT_TOKEN;
const channelId = process.env.TELEGRAM_CHANNEL_ID;

let bot: TelegramBot | null = null;

if (botToken && channelId) {
  bot = new TelegramBot(botToken, { polling: false });
  console.log('✅ Telegram bot initialized successfully');
} else {
  console.warn('⚠️ Telegram bot credentials not found. Telegram notifications will be disabled.');
}

interface InvestmentUpdate {
  investmentId: number;
  userId: number;
  userFirstName?: string;
  userLastName?: string;
  planName: string;
  profit: string;
  totalProfit: string;
  marketSource: string;
  transactionHash: string;
  timestamp: string;
}

interface NewInvestment {
  investmentId: number;
  userId: number;
  userFirstName?: string;
  userLastName?: string;
  planName: string;
  amount: string;
  duration: number;
  expectedROI: number;
  timestamp: string;
}

export async function sendInvestmentUpdateToChannel(update: InvestmentUpdate): Promise<void> {
  if (!bot || !channelId) {
    console.log('Telegram bot not configured, skipping channel update');
    return;
  }

  try {
    const userDisplay = update.userFirstName 
      ? `${update.userFirstName}${update.userLastName ? ' ' + update.userLastName : ''}` 
      : `User ${update.userId}`;

    const message = `🚀 *BITVAULT PRO LIVE UPDATE*

💰 *Investment Profit Generated*
👤 Investor: ${userDisplay}
📊 Plan: *${update.planName}*
💎 Investment ID: \`#${update.investmentId}\`

✅ *Latest Profit:* +${update.profit} BTC
📈 *Total Accumulated:* ${update.totalProfit} BTC
🔄 *Generated by:* ${update.marketSource}

🔐 Transaction: \`${update.transactionHash.substring(0, 16)}...\`
⏰ ${new Date(update.timestamp).toLocaleString('en-US', { 
  timeZone: 'UTC',
  dateStyle: 'medium',
  timeStyle: 'short'
})} UTC

*Automated returns delivered every 10 minutes* ⚡

\`#BitVaultPro #Bitcoin #Investment #Profit\``;

    await bot.sendMessage(channelId, message, { 
      parse_mode: 'Markdown',
      disable_web_page_preview: true 
    });
    
    console.log(`📱 Telegram update sent for investment #${update.investmentId}`);
  } catch (error) {
    console.error('❌ Failed to send Telegram update:', error);
  }
}

export async function sendNewInvestmentToChannel(investment: NewInvestment): Promise<void> {
  if (!bot || !channelId) {
    console.log('Telegram bot not configured, skipping channel update');
    return;
  }

  try {
    const userDisplay = investment.userFirstName 
      ? `${investment.userFirstName}${investment.userLastName ? ' ' + investment.userLastName : ''}` 
      : `User ${investment.userId}`;

    const message = `🌟 *NEW INVESTMENT ACTIVATED*

👤 *Investor:* ${userDisplay}
📈 *Plan:* ${investment.planName}
💰 *Amount:* ${investment.amount} BTC
⏱️ *Duration:* ${investment.duration} days
🎯 *Expected ROI:* ${investment.expectedROI}%

💎 *Investment ID:* \`#${investment.investmentId}\`

🚀 *Automated profit generation starts now!*
Returns will be delivered every 10 minutes ⚡

⏰ ${new Date(investment.timestamp).toLocaleString('en-US', { 
  timeZone: 'UTC',
  dateStyle: 'medium',
  timeStyle: 'short'
})} UTC

*Welcome to BitVault Pro professional investment platform* 🎉

\`#BitVaultPro #NewInvestment #Bitcoin #Trading\``;

    await bot.sendMessage(channelId, message, { 
      parse_mode: 'Markdown',
      disable_web_page_preview: true 
    });
    
    console.log(`📱 New investment notification sent for #${investment.investmentId}`);
  } catch (error) {
    console.error('❌ Failed to send new investment notification:', error);
  }
}

export async function sendDailyStatsToChannel(): Promise<void> {
  if (!bot || !channelId) {
    console.log('Telegram bot not configured, skipping daily stats');
    return;
  }

  try {
    const message = `📊 *BITVAULT PRO DAILY REPORT*

🔥 *Platform Statistics*
⚡ Automated returns: *Active*
🎯 Investment plans: *3 Available*
💎 Returns frequency: *Every 10 minutes*
🚀 Success rate: *99.9%*

📈 *Available Plans:*
• *Starter:* 0.2% daily (30 days)
• *Growth:* 0.5% daily (60 days)  
• *Premium:* 0.8% daily (90 days)

💰 *Join thousands of successful investors*
🔐 *Bank-grade security guaranteed*

⏰ ${new Date().toLocaleString('en-US', { 
  timeZone: 'UTC',
  dateStyle: 'full',
  timeStyle: 'short'
})} UTC

\`#BitVaultPro #DailyReport #Bitcoin #Investing\``;

    await bot.sendMessage(channelId, message, { 
      parse_mode: 'Markdown',
      disable_web_page_preview: true 
    });
    
    console.log('📱 Daily stats sent to Telegram channel');
  } catch (error) {
    console.error('❌ Failed to send daily stats:', error);
  }
}

export { bot };